export type TravelStatus = 'visited' | 'planned';

export type Country = {
  code: string;
  name: string;
  status: TravelStatus;
};

export const countries: Country[] = [
  { code: 'AM', name: 'Armenia', status: 'planned' },
  { code: 'AZ', name: 'Azerbaijan', status: 'planned' },
  { code: 'CY', name: 'Cyprus', status: 'planned' },
  { code: 'GE', name: 'Georgia', status: 'planned' },
  { code: 'IS', name: 'Iceland', status: 'planned' },
  { code: 'IE', name: 'Ireland', status: 'planned' },
  { code: 'KZ', name: 'Kazakhstan', status: 'planned' },
  { code: 'LI', name: 'Liechtenstein', status: 'planned' },
  { code: 'MT', name: 'Malta', status: 'planned' },
  { code: 'MC', name: 'Monaco', status: 'visited' },
  { code: 'GB', name: 'United Kingdom', status: 'planned' },
  { code: 'PT', name: 'Portugal', status: 'planned' },
  { code: 'RU', name: 'Russia', status: 'planned' },
  { code: 'SM', name: 'San Marino', status: 'planned' },
  { code: 'ES', name: 'Spain', status: 'planned' },
  { code: 'FR', name: 'France', status: 'visited' },
  { code: 'BE', name: 'Belgium', status: 'visited' },
  { code: 'NL', name: 'Netherlands', status: 'visited' },
  { code: 'LU', name: 'Luxembourg', status: 'planned' },
  { code: 'DE', name: 'Germany', status: 'visited' },
  { code: 'DK', name: 'Denmark', status: 'planned' },
  { code: 'NO', name: 'Norway', status: 'visited' },
  { code: 'SE', name: 'Sweden', status: 'visited' },
  { code: 'FI', name: 'Finland', status: 'visited' },
  { code: 'EE', name: 'Estonia', status: 'visited' },
  { code: 'LV', name: 'Latvia', status: 'planned' },
  { code: 'LT', name: 'Lithuania', status: 'planned' },
  { code: 'PL', name: 'Poland', status: 'visited' },
  { code: 'CZ', name: 'Czechia', status: 'visited' },
  { code: 'CH', name: 'Switzerland', status: 'visited' },
  { code: 'AT', name: 'Austria', status: 'visited' },
  { code: 'IT', name: 'Italy', status: 'visited' },
  { code: 'SI', name: 'Slovenia', status: 'planned' },
  { code: 'HR', name: 'Croatia', status: 'planned' },
  { code: 'HU', name: 'Hungary', status: 'planned' },
  { code: 'SK', name: 'Slovakia', status: 'planned' },
  { code: 'RO', name: 'Romania', status: 'planned' },
  { code: 'BG', name: 'Bulgaria', status: 'planned' },
  { code: 'GR', name: 'Greece', status: 'planned' },
  { code: 'TR', name: 'Turkey', status: 'planned' },
  { code: 'VA', name: 'Vatican City', status: 'planned' },
];

export const europeCountryNames = new Set([
  'Albania',
  'Andorra',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Kazakhstan',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Turkey',
  'Ukraine',
  'United Kingdom',
  'Vatican City',
]);

export const visitedPalette = ['#f2b347', '#ef9b38', '#f7c766', '#e8832f'] as const;

export const visitedCountries = countries.filter((country) => country.status === 'visited');
export const countryLookup = new Map(countries.map((country) => [country.name, country]));
export const visitedFillLookup = new Map(
  visitedCountries.map((country, index) => [country.name, visitedPalette[index % visitedPalette.length]]),
);
export const coverage = Math.round((visitedCountries.length / countries.length) * 100);
