export type TravelStatus = 'visited' | 'planned';

export type Country = {
  code: string;
  name: string;
  status: TravelStatus;
};

export type ContinentData = {
  title: string;
  countries: Country[];
  mapCountryNames: Set<string>;
  projection: {
    center: [number, number];
    scale: number;
  };
};

const europeCountries: Country[] = [
  { code: 'AM', name: 'Armenia', status: 'planned' },
  { code: 'AZ', name: 'Azerbaijan', status: 'planned' },
  { code: 'CY', name: 'Cyprus', status: 'planned' },
  { code: 'GE', name: 'Georgia', status: 'planned' },
  { code: 'IS', name: 'Iceland', status: 'planned' },
  { code: 'IE', name: 'Ireland', status: 'planned' },
  { code: 'KZ', name: 'Kazakhstan', status: 'planned' },
  { code: 'LI', name: 'Liechtenstein', status: 'planned' },
  { code: 'MT', name: 'Malta', status: 'planned' },
  { code: 'MC', name: 'Monaco', status: 'visited' },
  { code: 'GB', name: 'United Kingdom', status: 'planned' },
  { code: 'PT', name: 'Portugal', status: 'planned' },
  { code: 'RU', name: 'Russia', status: 'planned' },
  { code: 'SM', name: 'San Marino', status: 'planned' },
  { code: 'ES', name: 'Spain', status: 'planned' },
  { code: 'FR', name: 'France', status: 'visited' },
  { code: 'BE', name: 'Belgium', status: 'visited' },
  { code: 'NL', name: 'Netherlands', status: 'visited' },
  { code: 'LU', name: 'Luxembourg', status: 'planned' },
  { code: 'DE', name: 'Germany', status: 'visited' },
  { code: 'DK', name: 'Denmark', status: 'planned' },
  { code: 'NO', name: 'Norway', status: 'visited' },
  { code: 'SE', name: 'Sweden', status: 'visited' },
  { code: 'FI', name: 'Finland', status: 'visited' },
  { code: 'EE', name: 'Estonia', status: 'visited' },
  { code: 'LV', name: 'Latvia', status: 'planned' },
  { code: 'LT', name: 'Lithuania', status: 'planned' },
  { code: 'PL', name: 'Poland', status: 'visited' },
  { code: 'CZ', name: 'Czechia', status: 'visited' },
  { code: 'CH', name: 'Switzerland', status: 'visited' },
  { code: 'AT', name: 'Austria', status: 'visited' },
  { code: 'IT', name: 'Italy', status: 'visited' },
  { code: 'SI', name: 'Slovenia', status: 'planned' },
  { code: 'HR', name: 'Croatia', status: 'planned' },
  { code: 'HU', name: 'Hungary', status: 'planned' },
  { code: 'SK', name: 'Slovakia', status: 'planned' },
  { code: 'RO', name: 'Romania', status: 'planned' },
  { code: 'BG', name: 'Bulgaria', status: 'planned' },
  { code: 'GR', name: 'Greece', status: 'planned' },
  { code: 'TR', name: 'Turkey', status: 'planned' },
  { code: 'VA', name: 'Vatican City', status: 'planned' },
];

const asiaCountries: Country[] = [
  { code: 'AF', name: 'Afghanistan', status: 'planned' },
  { code: 'AM', name: 'Armenia', status: 'planned' },
  { code: 'AZ', name: 'Azerbaijan', status: 'planned' },
  { code: 'BH', name: 'Bahrain', status: 'planned' },
  { code: 'BD', name: 'Bangladesh', status: 'planned' },
  { code: 'BT', name: 'Bhutan', status: 'planned' },
  { code: 'BN', name: 'Brunei', status: 'planned' },
  { code: 'KH', name: 'Cambodia', status: 'planned' },
  { code: 'CN', name: 'China', status: 'planned' },
  { code: 'CY', name: 'Cyprus', status: 'planned' },
  { code: 'GE', name: 'Georgia', status: 'planned' },
  { code: 'IN', name: 'India', status: 'planned' },
  { code: 'ID', name: 'Indonesia', status: 'planned' },
  { code: 'IR', name: 'Iran', status: 'planned' },
  { code: 'IQ', name: 'Iraq', status: 'planned' },
  { code: 'IL', name: 'Israel', status: 'planned' },
  { code: 'JP', name: 'Japan', status: 'planned' },
  { code: 'JO', name: 'Jordan', status: 'planned' },
  { code: 'KZ', name: 'Kazakhstan', status: 'planned' },
  { code: 'KW', name: 'Kuwait', status: 'planned' },
  { code: 'KG', name: 'Kyrgyzstan', status: 'planned' },
  { code: 'LA', name: 'Laos', status: 'planned' },
  { code: 'LB', name: 'Lebanon', status: 'planned' },
  { code: 'MY', name: 'Malaysia', status: 'planned' },
  { code: 'MV', name: 'Maldives', status: 'planned' },
  { code: 'MN', name: 'Mongolia', status: 'planned' },
  { code: 'MM', name: 'Myanmar', status: 'planned' },
  { code: 'NP', name: 'Nepal', status: 'planned' },
  { code: 'KP', name: 'North Korea', status: 'planned' },
  { code: 'OM', name: 'Oman', status: 'planned' },
  { code: 'PK', name: 'Pakistan', status: 'planned' },
  { code: 'PH', name: 'Philippines', status: 'planned' },
  { code: 'QA', name: 'Qatar', status: 'visited' },
  { code: 'RU', name: 'Russia', status: 'planned' },
  { code: 'SA', name: 'Saudi Arabia', status: 'planned' },
  { code: 'SG', name: 'Singapore', status: 'visited' },
  { code: 'KR', name: 'South Korea', status: 'planned' },
  { code: 'LK', name: 'Sri Lanka', status: 'planned' },
  { code: 'SY', name: 'Syria', status: 'planned' },
  { code: 'TW', name: 'Taiwan', status: 'visited' },
  { code: 'TJ', name: 'Tajikistan', status: 'planned' },
  { code: 'TH', name: 'Thailand', status: 'visited' },
  { code: 'TL', name: 'Timor-Leste', status: 'planned' },
  { code: 'TR', name: 'Turkey', status: 'planned' },
  { code: 'TM', name: 'Turkmenistan', status: 'planned' },
  { code: 'AE', name: 'United Arab Emirates', status: 'planned' },
  { code: 'UZ', name: 'Uzbekistan', status: 'planned' },
  { code: 'VN', name: 'Vietnam', status: 'visited' },
  { code: 'YE', name: 'Yemen', status: 'planned' },
];

const europeCountryNames = new Set([
  'Albania',
  'Andorra',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Kazakhstan',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Turkey',
  'Ukraine',
  'United Kingdom',
  'Vatican City',
]);

const asiaCountryNames = new Set([
  'Afghanistan',
  'Armenia',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Bhutan',
  'Brunei',
  'Cambodia',
  'China',
  'Cyprus',
  'Georgia',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Israel',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Lebanon',
  'Malaysia',
  'Maldives',
  'Mongolia',
  'Myanmar',
  'Nepal',
  'North Korea',
  'Oman',
  'Pakistan',
  'Philippines',
  'Qatar',
  'Russia',
  'Saudi Arabia',
  'Singapore',
  'South Korea',
  'Sri Lanka',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Thailand',
  'Timor-Leste',
  'Turkey',
  'Turkmenistan',
  'United Arab Emirates',
  'Uzbekistan',
  'Vietnam',
  'Yemen',
]);

export const visitedPalette = ['#f2b347', '#ef9b38', '#f7c766', '#e8832f'] as const;

export const continents: ContinentData[] = [
  {
    title: 'Europe',
    countries: europeCountries,
    mapCountryNames: europeCountryNames,
    projection: {
      center: [8, 59],
      scale: 500,
    },
  },
  {
    title: 'Asia',
    countries: asiaCountries,
    mapCountryNames: asiaCountryNames,
    projection: {
      center: [92, 35],
      scale: 400,
    },
  },
];
